### PR TITLE
Make GLCalendarView respect the users locale

### PR DESCRIPTION
**Pull request by 3rdcycle**
Print day and month labels according to locale, respect the users first week day and expose
the view's calendar to make it configurable from the outside.

### CODE REVIEW

**Comment by ryh** [comment]
:+1: cool

**Comment by loicgriffie** [comment]
Do you plan du include this pull request ? Thanks

**Comment by ltebean** [comment]
I've updated the version to 1.1.0, thanks

**Comment by loicgriffie** [comment]
Thanks ! Very good component by the way :)

**Pull request merged**
